#!/bin/bash

# THIS SCRIPT IS NOT FOR FINAL USER
# CFG CAN BE OVERWRITTEN OR DAMAGED

WORKDIR="$(dirname "$PWD/$0")"

dosym() {
	ln -snf "$WORKDIR/${1}" "$HOME/${2}"
}

recdosym() {
	for i in $(ls -A $1); do
		dosym "$1/$i" "$2"
	done
	unset i
}

vimcfg() {
	recdosym "vim"
	! [ -e "~/.vim/bundle/Vundle.vim" ] && git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
	mkdir -p ~/.tmp
}


bashcfg() {
	recdosym "bash"
}


tmuxcfg() {
	dosym "tmux/.tmux.conf"
}


i3cfg() {
	dosym "i3" ".config"

	# i have problem with win key on my desktop pc
	if [ "$(nproc --all)" == "8" ]; then
		sed -i s'/set $mod Mod4/set $mod Mod1/'g "$HOME/.config/i3/config"
	elif [ "$(nproc --all)" == "2" ]; then
		sed -i s'/set $mod Mod1/set $mod Mod4/'g "$HOME/.config/i3/config"
	fi
}

gtkcfg() {
	dosym "gtk/.gtkrc-2.0"
}

rangercfg() {
	dosym "ranger" ".config"
}

icewmcfg() {
	dosym "icewm"
}

nanocfg() {
	dosym "nano/.nanorc"
}

ncmpcppcfg() {
	dosym "mpd/.mpd"
	dosym "ncmpcpp/.ncmpcpp"
}

dunstcfg() {
	dosym "dunst" ".config"
}

comptoncfg() {
	dosym "compton/compton.conf" ".config"
}

conkycfg() {
	dosym "conky" ".config"
}

fvwmcfg() {
dosym "fvwm" ".fvwm"

}

vimcfg
nanocfg
bashcfg
tmuxcfg
i3cfg
gtkcfg
rangercfg
icewmcfg
ncmpcppcfg
dunstcfg
comptoncfg
conkycfg
fvwmcfg
