#!/bin/bash

# THIS SCRIPT IS NOT FOR FINAL USER
# CFG CAN BE OVERWRITTEN OR DAMAGED

WORKDIR="$(dirname "$PWD/$0")"

dosym() {
	ln -snf "$WORKDIR/${1}" "$HOME/${2}"
}

recdosym() {
	for i in $(ls -A $1); do
		dosym "$1/$i" "$2"
	done
	unset i
}

vimcfg() {
	recdosym "vim"
	! [ -e "~/.vim/bundle/Vundle.vim" ] && git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
	mkdir -p ~/.tmp
}


bashcfg() {
	recdosym "bash"
}


tmuxcfg() {
	dosym "tmux/.tmux.conf"
}


i3cfg() {
	dosym "i3" ".config"
}

gtkcfg() {
	dosym "gtk/.gtkrc-2.0"
	mkdir -p ~/.config/gtk-3.0
	dosym "gtk/settings.ini" ".config/gtk-3.0/settings.ini"
}

rangercfg() {
	dosym "ranger" ".config"
}

icewmcfg() {
	dosym "icewm"
}

nanocfg() {
	dosym "nano/.nanorc"
}

ncmpcppcfg() {
	dosym "mpd/.mpd"
	dosym "ncmpcpp/.ncmpcpp"
}

dunstcfg() {
	dosym "dunst" ".config"
}

comptoncfg() {
	dosym "compton/compton.conf" ".config"
}

conkycfg() {
	dosym "conky" ".config"
}

fvwmcfg() {
	dosym "fvwm" ".fvwm"
}

polybarcfg() {
	dosym "polybar" ".config"
}

ratpoisoncfg() {
	dosym "ratpoison/.ratpoisonrc"
}

spectrwmcfg() {
	dosym "spectrwm/.spectrwm.conf"
}


vimcfg
nanocfg
bashcfg
tmuxcfg
i3cfg
gtkcfg
rangercfg
icewmcfg
ncmpcppcfg
dunstcfg
comptoncfg
conkycfg
fvwmcfg
polybarcfg
ratpoisoncfg
spectrwmcfg
